# Site settings
title: ParadiseHell
SEOTitle: 程涛的博客 | ChengTao Blog
header-img: img/home-bg.jpg
email: tao@paradisehell.org
description: "ChengTao 的博客"
keyword: "PradiseHell,ChengTao Blog"
url: "http://paradisehell.org"              
baseurl: "" 



# SNS settings
RSS: false
zhihu_username:     cheng-tao-36-94
github_username:    ParadiseHell 
twitter_username:   ctparadisehell
facebook_username:  ctparadisehell



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins:
 - jekyll-paginate



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: ctparadisehell


# Analytics settings
# Baidu Analytics
ba_track_id: 7f2e2fc6a3d029e4ee5d05c419df70bc
# Google Analytics
ga_track_id: 'UA-137823949-1'
ga_domain: paradisehell.org



# Sidebar settings
sidebar: true
sidebar-about-description: "Know the unknown."
sidebar-avatar: /img/paradisehell-avatar.jpeg


# Featured Tags
featured-tags: true 
featured-condition-size: 1 


# Friends
friends: [
]
